# Generated by Django 5.2.4 on 2025-09-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerpass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='eh_valido',
            field=models.BooleanField(default=True, help_text='Indica se o registro de ponto é válido (ex: uma entrada que possui uma saída correspondente).'),
        ),
    ]
