# Generated by Django 5.2.4 on 2025-09-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerpass', '0002_ponto_eh_valido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='data_hora_do_ponto',
            field=models.DateTimeField(),
        ),
    ]
