name: CI Makerpass

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ] 

jobs:
  
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip

          pip install -r requirements.txt
          
      - name: Verificar código deprecado
        run: |
          echo "🔍 Verificando código Python deprecado..."
          deprecation-linter --path=. --exit-on-error

      - name: Executar OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'makerpass-project'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --failOnCVSS 7
            
      - name: Upload do Relatório de Scan
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports


  








